name = "NoisyReach"
uuid = "caa4e8f2-8139-4784-bc83-fd977aec17f5"
authors = ["Shengjie Xu <shengjiex98@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
ReachabilityAnalysis = "1e97bd63-91d1-579d-8e8d-501d2b57c93f"

[compat]
julia = "1.6.7"

[extras]
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ControlSystemsBase", "LinearAlgebra", "Test"]
